language: python
python:
- '2.7'
- '3.3'
sudo: required
apt_addons:
- wget
services:
- docker
before_install:
install:
- pip install testinfra
before_script:
- docker-compose build
- docker-compose up -d
script:
- pip install testinfra
- pip install pytest-flask
before_cache:
after_success:
- docker-compose down
after_failure:
before_deploy:
deploy:
after_deploy:
after_script: